name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: cd RoleAndManagement && dotnet restore

    - name: Build project
      run: cd RoleAndManagement && dotnet build --no-restore

    - name: Run tests (optional)
      run: cd RoleAndManagement && dotnet test --no-build --verbosity normal
      # continue-on-error: true
